target: web

template:
  path: client/index.html
  meta:
    url: "https://elenapavel.github.io/portfolio"
    title: "Portfolio - Elena Pavel"
    description: "A small playground for React learning"

alias:
  $website: ~/client/website

# Production #

url:
  path: /portfolio